//! Backward-compatibility tests: M2 `.thx` artifacts under M3 sim code.
//!
//! These tests verify the **mechanical** guarantee that:
//! 1. Frozen M2 artifacts (format_version = "m2-draft", no `dt_ms` in metadata)
//!    still load and simulate byte-identically under M3 Rust code.
//! 2. M3 artifacts (same format_version, `dt_ms` added to metadata) also load
//!    correctly — proves `ThxMetadata` has no `deny_unknown_fields` that would
//!    silently break on extra fields.
//! 3. The M3 compiler's output for an identical model (same architecture, weights,
//!    and alpha) produces bit-identical simulation output to the M2 fixture.
//!
//! If any of these tests fail, check whether `deny_unknown_fields` was added to
//! a sim model struct.  If loading genuinely breaks, bump `format_version` and
//! gate (do NOT silently widen the struct).

use thrindex_sim::model::{ResolvedModel, load_from_str};
use thrindex_sim::sim::{SimConfig, run};

/// Frozen M2 `.thx` fixture — Dense(2→2 identity) + LIF(tau_mem=10ms).
///
/// Generated by the M2 compile.py on 2026-01-01. This file MUST NOT be edited;
/// if the sim code starts rejecting it, the format contract has been broken.
const M2_FIXTURE: &str = include_str!("fixtures/m2_dense_lif.thx");

/// Same artifact with `dt_ms: 1.0` injected into metadata (simulates M3 output).
///
/// If this loads but M2_FIXTURE does not, there is a bug in the M3 path.
/// If this fails to load, it means `ThxMetadata` has gained `deny_unknown_fields`
/// — that is a breaking change and requires a `format_version` bump.
const M3_DT_MS_FIXTURE: &str = include_str!("fixtures/m3_with_dt_ms.thx");

// ── Helper ────────────────────────────────────────────────────────────────────

fn run_2x2_identity(model: &ResolvedModel) -> Vec<Vec<Vec<f32>>> {
    // 1 sample × 1 timestep × 2 features.
    // Input [1.0, 1.0] → Dense identity → [1.0, 1.0] → LIF(threshold=1.0).
    // After spike: mem is reset; both neurons fire.
    let input = vec![vec![vec![1.0f32, 1.0f32]]];
    let cfg = SimConfig::default();
    run(model, &input, &cfg)
        .expect("sim should succeed on M2 fixture")
        .spikes
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[test]
fn m2_fixture_loads() {
    // PRIMARY BACKWARD-COMPAT CHECK.
    // If this fails, the M2 format contract has been broken under M3 code.
    load_from_str(M2_FIXTURE)
        .expect("M2 fixture must load under M3 sim code without any format change");
}

#[test]
fn m3_dt_ms_fixture_loads() {
    // Proves ThxMetadata has no deny_unknown_fields — extra `dt_ms` is silently ignored.
    // If this fails, deny_unknown_fields was added somewhere it should not be.
    load_from_str(M3_DT_MS_FIXTURE).expect(
        "M3 artifact with dt_ms in metadata must load — ThxMetadata must not deny unknown fields",
    );
}

#[test]
fn m2_and_m3_simulate_identically() {
    // Both fixtures contain identical model weights and alpha.
    // Simulating them must yield bit-identical output.
    let m2 = load_from_str(M2_FIXTURE).expect("M2 load");
    let m3 = load_from_str(M3_DT_MS_FIXTURE).expect("M3 load");

    let spikes_m2 = run_2x2_identity(&m2);
    let spikes_m3 = run_2x2_identity(&m3);

    assert_eq!(
        spikes_m2, spikes_m3,
        "M2 and M3 artifacts must produce bit-identical simulation output for identical models",
    );
}

#[test]
fn m2_fixture_spike_output_is_frozen() {
    // Frozen expected output: Dense identity(2→2), threshold=1.0, input=[1,1].
    // Both neurons fire on the first (and only) timestep → spikes = [1.0, 1.0].
    let model = load_from_str(M2_FIXTURE).expect("M2 load");
    let spikes = run_2x2_identity(&model);

    // shape: [1 sample][1 timestep][2 neurons]
    assert_eq!(spikes.len(), 1, "1 sample");
    assert_eq!(spikes[0].len(), 1, "1 timestep");
    assert_eq!(spikes[0][0], vec![1.0f32, 1.0f32], "both neurons fire");
}

#[test]
fn m3_compiler_output_matches_m2_simulation() {
    // Verify that the M3 Rust compiler produces an artifact whose simulation output
    // is byte-identical to the M2 fixture (same architecture, same weights, same alpha).
    //
    // This is the "differential test for zero-delay backward-compat" promised in the plan.
    use base64::{Engine as _, engine::general_purpose::STANDARD as B64};
    use thrindex_compiler::compile;

    // Identity 2×2 weights: [1.0, 0.0, 0.0, 1.0] f32 LE
    let weights_bytes: Vec<u8> = [1.0f32, 0.0f32, 0.0f32, 1.0f32]
        .iter()
        .flat_map(|f| f.to_le_bytes())
        .collect();
    let weights_b64 = B64.encode(&weights_bytes);

    let ir = serde_json::json!({
        "dt_ms": 1.0,
        "layers": [
            {
                "type": "dense",
                "in_features": 2,
                "out_features": 2,
                "weights_b64": weights_b64,
                "bias_b64": null,
                "delays": null
            },
            {
                "type": "lif",
                "tau_mem": 10.0,
                "tau_syn": null,
                "threshold": 1.0,
                "reset": "subtract"
            }
        ]
    });

    let report = compile(&ir.to_string(), "sim").expect("M3 compile should succeed");
    assert!(
        report.advisory.is_none(),
        "no retiming advisory for same-dt compile"
    );

    let m3_model = load_from_str(&report.thx_json).expect("M3 artifact loads");
    let m2_model = load_from_str(M2_FIXTURE).expect("M2 fixture loads");

    let spikes_m3 = run_2x2_identity(&m3_model);
    let spikes_m2 = run_2x2_identity(&m2_model);

    assert_eq!(
        spikes_m3, spikes_m2,
        "M3 compiler output must simulate identically to M2 fixture for zero-delay models",
    );
}
