//! `thrindex._core` — the compiled Rust extension module.
//!
//! This crate is intentionally thin: **zero SNN logic lives here**.  All
//! computation belongs in `thrindex-sim` and future core crates, consumed via
//! re-exports.
//!
//! Python consumers (correction 3 / ARCHITECTURE.md): `thx.run()` calls
//! `_core.run_sim(...)` through this bridge.  The CLI binary (`thrindex-cli`) is a
//! separate peer consumer of `thrindex-sim` — neither calls the other.

#![deny(unsafe_code)]
#![warn(clippy::pedantic)]

use std::collections::HashMap;

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use thrindex_sim::{SimConfig, model, raster::SpikeRaster, sim};

// ── Module ────────────────────────────────────────────────────────────────────

/// The `thrindex._core` Python extension module.
///
/// Exposed callables:
/// - `run_sim(artifact_path, input_spikes, threads, seed) -> (spikes, stats, transcript)`
/// - `check_artifact(path) -> None  # raises on error`
#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
    m.add_function(wrap_pyfunction!(run_sim, m)?)?;
    m.add_function(wrap_pyfunction!(check_artifact, m)?)?;
    Ok(())
}

// ── run_sim ───────────────────────────────────────────────────────────────────

/// Run the behavioral simulator and return the rendered §29 transcript.
///
/// Parameters
/// ----------
/// artifact_path : str
///     Path to the `.thx` artifact on disk.
/// input_spikes : list[list[list[float]]]
///     Shape `[batch, timesteps, in_features]`.  Must be pre-generated by the
///     encoder stage; **the simulator contains no RNG** (correction 2).
/// threads : int
///     Thread count.  0 = Rayon default.  1 = sequential.
/// seed : int
///     Encoder seed passed through for transcript provenance only.
///
/// Returns
/// -------
/// (spikes, stats_dict, transcript)
///     `spikes`     : list[list[list[float]]] — shape `[batch, T, out]`.
///     `stats_dict` : dict with keys `total_spikes`, `synaptic_ops`, `wall_secs`.
///     `transcript` : str — the §29-format transcript rendered in Rust.
#[pyfunction]
#[pyo3(signature = (artifact_path, input_spikes, threads=0, seed=0))]
fn run_sim(
    artifact_path: &str,
    input_spikes: Vec<Vec<Vec<f32>>>,
    threads: usize,
    seed: u64,
) -> PyResult<(Vec<Vec<Vec<f32>>>, HashMap<String, f64>, String)> {
    let resolved = model::load(artifact_path).map_err(|e| PyValueError::new_err(e.to_string()))?;

    let config = SimConfig { threads };
    let output = sim::run(&resolved, &input_spikes, &config)
        .map_err(|e| PyValueError::new_err(e.to_string()))?;

    // Build raster for transcript rendering (first sample only).
    let in_features = input_spikes
        .first()
        .and_then(|s| s.first())
        .map_or(0, |f| f.len());
    let raster = SpikeRaster::from_frames(
        output.spikes.first().cloned().unwrap_or_default(),
        in_features,
    );

    let transcript = sim::render_transcript(
        &resolved,
        &output,
        &raster,
        Some(seed),
        env!("CARGO_PKG_VERSION"),
    );

    let spikes = output.spikes.clone();
    let mut stats: HashMap<String, f64> = HashMap::new();
    stats.insert("total_spikes".to_string(), output.stats.total_spikes as f64);
    stats.insert("synaptic_ops".to_string(), output.stats.synaptic_ops as f64);
    stats.insert("wall_secs".to_string(), output.stats.wall_secs);

    Ok((spikes, stats, transcript))
}

// ── check_artifact ────────────────────────────────────────────────────────────

/// Verify that a `.thx` artifact is readable and passes the CRC32 integrity check.
///
/// Raises `ValueError` carrying the `E####` message if the artifact is invalid.
/// Returns `None` on success.
#[pyfunction]
fn check_artifact(path: &str) -> PyResult<()> {
    model::load(path).map_err(|e| PyValueError::new_err(e.to_string()))?;
    Ok(())
}
